print("Marella Buhay")
print("Hupi, Santa Cruz, Marinduque")
print("September 17, 2001")
print("College of Engineering, Information and Industrial Technology")
print("Bachelor of Science in Information Technology")
print("Second Year")
print("Section- B")
print("Drawing")
print("Listen to Music")
print("Play Mobile Games")
print("Watch Horror Films")
print("Read Comics")
